version: "3"

services:
  mysql-5.7-3306:
    container_name: mysql-5.7-3306
    image: mysql:5.7
    expose:
      - 3306
    ports:
      - 3306:3306
    volumes:
      - "./docs/data/mysql:/var/lib/mysql"
    command: --default-authentication-plugin=mysql_native_password # 解决php数据库连接不上的问题
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: "123456"
      TZ: Asia/Shanghai 
  
  redis-5.0-6379:
    container_name: redis-5.0-6379
    image: redis:5.0
    expose:
      - 6379
    ports:
      - 6379:6379
    volumes:
      - "./docs/data/redis:/data"
    restart: always

  memcached-1.6-11211:
    container_name: memcached-1.6-11211
    image: memcached:1.6
    expose:
      - 11211
    ports:
      - 11211:11211
    restart: always

  taurus-demo:
    container_name: taurus-demo
    build: .
    image: taurus-demo
    expose:
      - 80
    volumes:
      - ".:/code_root"
    restart: always
    environment:
      VIRTUAL_HOST: www.examples.com,admin.examples.com,api.examples.com
      RAURUS_ENV: develop
    # command: -v /etc/localtime:/etc/localtime:ro

# docker network create nginx-proxy
# docker run -d -p 80:80 --name nginx-proxy --network nginx-proxy --restart always -v /var/run/docker.sock:/tmp/docker.sock jwilder/nginx-proxy
networks:
  default:
    external:
      name: nginx-proxy